### ISSUE TITLE
[Suggestion] Add Incursion Timers

### ISSUE THREAD

**Issue by wheatbread** [funkydude/LegionInvasionTimer#75]
Hello!  Thank you for your work on this addon!

Might it be possible for you to add timers for the new 8.1 faction assaults (formerly called incursions) as well?

**Comment by funkydude** [comment]
It would be possible if there is a specific timer on the assaults. It will take some time to figure it out.

**Comment by rozynrot** [comment]
Here's the current doc loadout for the Timer for Faction assaults. Basically it's the same downtimer as legion assaults but lasts an hour longer: 

https://docs.google.com/spreadsheets/d/1Fz10_sMlsyBTaJtRhtRf2OJyP5RA5ez-pX3tpEhmc0s/edit#gid=0

I also would love to see this rolled into your addon as well. Used it throughout legion.

**Comment by funkydude** [comment]
@rozynrot That spreadsheet seems to suggest the downtime is 12 hours, but it was 12.5 hours for Legion. It does however confirm that it lasts one hour longer, 7 hours instead of 6 hours.

I am now working on a separate "BFAInvasionTimer" addon for this and assuming the spreadsheet is correct for now.

**Comment by FuxieDK** [comment]
> I am now working on a separate "BFAInvasionTimer" addon for this and assuming the spreadsheet is correct for now.

ETA on this AddOn? I cannot imagine it will take long to make, based on Legion timer..

**Comment by funkydude** [comment]
https://github.com/funkydude/BFAInvasionTimer
